### ISSUE TITLE
else change to elseif

### ISSUE THREAD

**Issue by Albertc** [ianhattendorf/autocomplete-ruby#8]
when typing `else`:

![image](https://cloud.githubusercontent.com/assets/124529/19153296/38a2b1b0-8bd6-11e6-915a-d89c6cc9a9db.png)

and when you press enter, or choose with mouse "else":

![image](https://cloud.githubusercontent.com/assets/124529/19153279/25381840-8bd6-11e6-8543-b21c8bf0c210.png)

**Comment by Mexxerio** [comment]
@Albertc This has nothing to do with this package but with https://github.com/atom/autocomplete-plus

Please create an issue there.

**Comment by ianhattendorf** [comment]
Could this have been due to the old provider? Either way I've just published version 0.2.0, you could try that and see if it changes anything.

**Comment by Albertc** [comment]
I have disabled autocomplete-plus and still happens.
Si for my experience the problem is in language-ruby and language-ruby-on-rails, both causes this problem, 
Or this is what it seems, when enable one to one, for example
![image](https://cloud.githubusercontent.com/assets/124529/19553570/0306066c-96b5-11e6-99cd-9421a53a0ef1.png)

I have this issue in atom with windows and atom with ubuntu

**Comment by Albertc** [comment]
It seems, **rails-snippets** package is what causes this issue, sorry and thanks
I will move this issue there
